### PR TITLE
Feature/new application endpoint

### PR DESCRIPTION
**Pull request by dannil76**

### CODE REVIEW

**Comment by dannil76** [comment]
> Error in post body while sending post data to viva/applications
> 
> TypeError: {[http://ilab.se/VivaApplication}PERSON()](http://ilab.se/VivaApplication%7DPERSON()) got an unexpected keyword argument 'FOREGINCITIZEN'. Signature: `PNUMBER: xsd:string, FNAME: xsd:string, LNAME: xsd:string, ADDRESSES: {http://ilab.se/VivaApplication}ARRAYOFADDRESS, PHONENUMBERS: {http://ilab.se/VivaApplication}ARRAYOFPHONE, EMAIL: {http://ilab.se/VivaApplication}EMAILADDRESS, FOREIGNCITIZEN: xsd:boolean, RESIDENCEPERMITTYPE: xsd:string, RESIDENCEPERMITDATE: xsd:string, CIVILSTATUS: xsd:string, ALTCIVILSTATUS: xsd:string`

Trying to reproduce the error message without success ?! When I post to test numbers ending in 5852, I get the following response:
`{
  "ERRORCODE": "1014",
  "ERRORMESSAGE": "Status (16) tillåter inte inlämnande av ansökan.",
  "ID": null,
  "IDENCLAIR": null,
  "STATUS": "Error"
}`

This must mean that the person already has a request for the basic application active?

**Comment by TeddyAndersson** [comment]
Then i would like to know the difference in the json body that we pass to the application, becouse thats what Viva complains about in the end

**Comment by TeddyAndersson** [comment]
New error after changing the json body

zeep.exceptions.XMLSyntaxError: Invalid XML content received (Space required after the Public Identifier, line 1, column 63)

**Comment by TeddyAndersson** [comment]
The mock data might not be correct, please check and update if there is anything missing.

**Pull request merged**
