### PR TITLE
Feat/mypages operation booked payments

### PR DESCRIPTION
**Pull request by dannil76**
Added viva operation PERSONBOOKEDPAYMENTS

Setup and run app as described in README.md

GET request as follow
http://127.0.0.1:5000/viva/mypages/[hashid]

Expected result
json respons should now include something like this
`"booked_payments": {
    "status": "1",
    "payments": null
},`

### CODE REVIEW

**Comment by TeddyAndersson** [comment]
Could you in short terms explain to me what have been added and what i need to test 😄

**Comment by dannil76** [comment]
> Could you in short terms explain to me what have been added and what i need to test 😄

PR info updated

**Comment by TeddyAndersson** [comment]
When trying to send a get request on my/request/{pnohash}, i'm getting the following error. Don't know where this is coming from, a guess is that it's due to serialization from xml to json. But as stated earlier i'm very uncertain.

TypeError: Object of type _Element is not JSON serializable

**Comment by dannil76** [comment]
> When trying to send a get request on my/request/{pnohash}, i'm getting the following error. Don't know where this is coming from, a guess is that it's due to serialization from xml to json. But as stated earlier i'm very uncertain.
> 
> TypeError: Object of type _Element is not JSON serializable

Fixed on testserver https://viva-adapter.helsingborg.io/viva/mypages/[hashid]

**Pull request merged**
